// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cohnehlyehynzkgteslf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaG5laGx5ZWh5bnprZ3Rlc2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTg1MDYsImV4cCI6MjA3NDEzNDUwNn0.wH_fQ5em20B0RaF_aEYNUdRFtcly6GRLEcdaH28XLXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);